//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace NVIDIA.PhysX {

public partial class PxCapsuleControllerDesc : PxControllerDesc {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal PxCapsuleControllerDesc(global::System.IntPtr cPtr, bool cMemoryOwn) : base(NativePINVOKE.PxCapsuleControllerDesc_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(PxCapsuleControllerDesc obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  public override void destroy() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          NativePINVOKE.delete_PxCapsuleControllerDesc(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.destroy();
    }
  }

  public PxCapsuleControllerDesc() : this(NativePINVOKE.new_PxCapsuleControllerDesc__SWIG_0(), true) {
    if (NativePINVOKE.SWIGPendingException.Pending) throw NativePINVOKE.SWIGPendingException.Retrieve();
  }

  public PxCapsuleControllerDesc(PxCapsuleControllerDesc arg0) : this(NativePINVOKE.new_PxCapsuleControllerDesc__SWIG_1(PxCapsuleControllerDesc.getCPtr(arg0)), true) {
    if (NativePINVOKE.SWIGPendingException.Pending) throw NativePINVOKE.SWIGPendingException.Retrieve();
  }

  public PxCapsuleControllerDesc __assign(PxCapsuleControllerDesc arg0) {
    PxCapsuleControllerDesc ret = new PxCapsuleControllerDesc(NativePINVOKE.PxCapsuleControllerDesc___assign(swigCPtr, PxCapsuleControllerDesc.getCPtr(arg0)), false);
    if (NativePINVOKE.SWIGPendingException.Pending) throw NativePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual void setToDefault() {
    NativePINVOKE.PxCapsuleControllerDesc_setToDefault(swigCPtr);
    if (NativePINVOKE.SWIGPendingException.Pending) throw NativePINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual bool isValid() {
    bool ret = NativePINVOKE.PxCapsuleControllerDesc_isValid(swigCPtr);
    if (NativePINVOKE.SWIGPendingException.Pending) throw NativePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public float radius {
    set {
      NativePINVOKE.PxCapsuleControllerDesc_radius_set(swigCPtr, value);
      if (NativePINVOKE.SWIGPendingException.Pending) throw NativePINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      float ret = NativePINVOKE.PxCapsuleControllerDesc_radius_get(swigCPtr);
      if (NativePINVOKE.SWIGPendingException.Pending) throw NativePINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public float height {
    set {
      NativePINVOKE.PxCapsuleControllerDesc_height_set(swigCPtr, value);
      if (NativePINVOKE.SWIGPendingException.Pending) throw NativePINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      float ret = NativePINVOKE.PxCapsuleControllerDesc_height_get(swigCPtr);
      if (NativePINVOKE.SWIGPendingException.Pending) throw NativePINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

}

}
