//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace NVIDIA.PhysX {

public enum PxControllerDebugRenderFlag : uint {
  TEMPORAL_BV = (1 << 0),
  CACHED_BV = (1 << 1),
  OBSTACLES = (1 << 2),
  NONE = 0,
  ALL = 0xffffffff
}

}
