//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace NVIDIA.PhysX {

public enum PxVehicleDifferential4WData {
  DIFF_TYPE_LS_4WD,
  DIFF_TYPE_LS_FRONTWD,
  DIFF_TYPE_LS_REARWD,
  DIFF_TYPE_OPEN_4WD,
  DIFF_TYPE_OPEN_FRONTWD,
  DIFF_TYPE_OPEN_REARWD,
  MAX_NB_DIFF_TYPES
}

}
