//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace NVIDIA.PhysX {

public enum PxVehicleDriveGraphChannel {
  ENGINE_REVS = 0,
  ENGINE_DRIVE_TORQUE,
  CLUTCH_SLIP,
  ACCEL_CONTROL,
  BRAKE_CONTROL,
  HANDBRAKE_CONTROL,
  STEER_LEFT_CONTROL,
  STEER_RIGHT_CONTROL,
  GEAR_RATIO,
  MAX_NB_DRIVE_CHANNELS
}

}
