//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace NVIDIA.PhysX {

public enum PxVehicleGearsDataEnum {
  REVERSE = 0,
  NEUTRAL,
  FIRST,
  SECOND,
  THIRD,
  FOURTH,
  FIFTH,
  SIXTH,
  SEVENTH,
  EIGHTH,
  NINTH,
  TENTH,
  ELEVENTH,
  TWELFTH,
  THIRTEENTH,
  FOURTEENTH,
  FIFTEENTH,
  SIXTEENTH,
  SEVENTEENTH,
  EIGHTEENTH,
  NINETEENTH,
  TWENTIETH,
  TWENTYFIRST,
  TWENTYSECOND,
  TWENTYTHIRD,
  TWENTYFOURTH,
  TWENTYFIFTH,
  TWENTYSIXTH,
  TWENTYSEVENTH,
  TWENTYEIGHTH,
  TWENTYNINTH,
  THIRTIETH,
  GEARSRATIO_COUNT
}

}
