//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace NVIDIA.PhysX {

public enum PxVehicleWheelGraphChannel {
  JOUNCE,
  SUSPFORCE,
  TIRELOAD,
  NORMALIZED_TIRELOAD,
  WHEEL_OMEGA,
  TIRE_FRICTION,
  TIRE_LONG_SLIP,
  NORM_TIRE_LONG_FORCE,
  TIRE_LAT_SLIP,
  NORM_TIRE_LAT_FORCE,
  NORM_TIRE_ALIGNING_MOMENT,
  MAX_NB_WHEEL_CHANNELS
}

}
