//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace NVIDIA.PhysX {

[global::System.FlagsAttribute()]
public enum PxVehicleWheelsSimFlags {
  LIMIT_SUSPENSION_EXPANSION_VELOCITY = (1 << 0),
  DISABLE_INTERNAL_CYLINDER_PLANE_INTERSECTION_TEST = (1 << 1),
  DISABLE_SUSPENSION_FORCE_PROJECTION = (1 << 2)
}

}
