//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace NVIDIA.PhysX {

public enum PxVehicleDrive4WControl {
  ANALOG_INPUT_ACCEL = 0,
  ANALOG_INPUT_BRAKE,
  ANALOG_INPUT_HANDBRAKE,
  ANALOG_INPUT_STEER_LEFT,
  ANALOG_INPUT_STEER_RIGHT,
  MAX_NB_DRIVE4W_ANALOG_INPUTS
}

}
